### ISSUE TITLE
bugfix CPF inválido

### ISSUE THREAD

**Issue by MattSaito** [Victor-Briganti/PIFrontend#60]
alguns cpfs não são aceitos

![Image](https://github.com/user-attachments/assets/dbe9d593-7109-4cd8-ae15-5e41c8ae6bcc)

050.676.970-40

**Comment by Victor-Briganti** [comment]
E lá vamos nós

605.576.830-50



![Image](https://github.com/user-attachments/assets/a3b273c2-2942-4cbe-afe6-efe1210d8ac7)
